# Environment configurations
language: node_js
node_js: '8'
os: osx
osx_image: xcode10.1

# Build condition
if: tag IS present

before_install:
  - source ./build-scripts/env.sh

install:
  - echo "Skipping yarn install"
#   - yarn install

script:
  - sh build-scripts/build.sh
