# Environment configurations
os: osx
osx_image: xcode10.1

language: node_js
node_js: '8'
cache: yarn

notifications:
  slack:
    rooms:
      - thichlammoc:KDr6DywMVHkRt21ZFIgy9Iom
    on_start: always # default: never
    on_success: change # default: always
    on_failure: always # default: always

# Build condition
if: tag IS present

before_install:
  - openssl aes-256-cbc -K $encrypted_d35e2d5c767f_key -iv $encrypted_d35e2d5c767f_iv -in api-android-playstore.json.enc -out api-android-playstore.json -d
  - source ./build-scripts/env.sh

install:
  - yarn install

script:
  - sh build-scripts/build.sh
