# Environment configurations
os: osx
osx_image: xcode10.1

language: node_js
node_js: '8'
cache: yarn

# Build condition
if: tag IS present

before_install:
  - source ./build-scripts/env.sh

install:
  - yarn install

script:
  - sh build-scripts/build.sh
