# Environment configurations
language: node_js
node_js: '8'
os: osx

# Build condition
if: tag IS present

before_install:
  - source ./build-scripts/env.sh

install:
  - sudo gem install fastlane
  - yarn install

script:
  - sh build-scripts/build.sh
